import GlobalProvider from "@/components/Application/GlobalProvider";
import { ThemeProvider } from "@/components/Application/ThemeProvider";
import "./globals.css";
import { Assistant } from 'next/font/google'
import { ToastContainer } from "react-toastify";

const assistantFont = Assistant({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${assistantFont.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <GlobalProvider>
            <ToastContainer />
            {children}
          </GlobalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
